### ISSUE TITLE
Function to generate sum-of-variables formula

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-tools#23]
Would be of the format `list[str] -> function[entity, period, parameters -> float]`

And then invoked via:
```python
class variable(Variable):
  ...

  formula = sum_of_variables([var1, var2])
```

**Comment by MaxGhenis** [comment]
Nice idea. Two questions:
1. Would all variables have to be at the same entity as the variable, or could it do a mix of `add` and `aggr` behind the scenes?
2. Could the set of variables come from a parameter?

**Comment by nikhilwoodruff** [comment]
I think:
1. `add` will enable either entity level.
2. Nice idea, will implement
