### ISSUE TITLE
`sum_of_variables` doesn't work with variables at different aggregate entity levels

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-tools#49]
See [this notebook](https://colab.research.google.com/drive/1pPFfcHY2Zpy8Lw1jb06mckroqAs87Ahq?usp=sharing), where I'm trying to add a tax-unit-level variable (`gi21`) and add it to `spm_unit_benefits` by adding it to the `sum_of_variables`.

When running `calc` after doing this, I get an error:
>ValueError: You tried to compute the variable 'gi21' for the entity 'people'; however the variable 'gi21' is defined for 'tax_units'.

**Comment by nikhilwoodruff** [comment]
This is fixed now, right? The notebook runs for me.
